# permissions for end users to view demoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-viewer-role
rules:
- apiGroups:
  - tutorial.demo.com
  resources:
  - demoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.demo.com
  resources:
  - demoes/status
  verbs:
  - get
