---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tutorial-demo-com-v1-demo
  failurePolicy: Fail
  name: mdemo.kb.io
  rules:
  - apiGroups:
    - tutorial.demo.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - demoes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tutorial-demo-com-v1-demo
  failurePolicy: Fail
  name: vdemo.kb.io
  rules:
  - apiGroups:
    - tutorial.demo.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - demoes
  sideEffects: None
