logging:
  level:
    root: "info"
    com.yunsheng.redis: "info"
spring:
  redis:
    database: 10 #使用哪一个库，默认是0号库
    host: 10.206.97.16
    port: 6380
    password: U]3uR[Uce[]8xu6I
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制
        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  # 连接池中的最大空闲连接
        min-idle: 10 # 连接池中的最小空闲连接
    timeout: 3000 # 读超时时间（毫秒）
    connect-timeout: 2000 # 链接超时时间（毫秒）
