

logging:
  level:
    root: "debug"
    com.yunsheng.redis: "debug"
#    单节点模式
spring:
  redis:
#    database: 10 #使用哪一个库，默认是0号库
    host: 10.138.42.38
    port: 6395
    password: syfdgh
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制
        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  # 连接池中的最大空闲连接
        min-idle: 10 # 连接池中的最小空闲连接
    timeout: 3000 # 读超时时间（毫秒）
    connect-timeout: 2000 # 链接超时时间（毫秒）


# 链接集群
#spring:
#  redis:
#    cluster:
##      nodes: 10.250.132.66:6379,10.250.132.67:6379,10.250.132.68:6379,10.250.133.193:6379,10.250.133.195:6379,10.250.133.198:6379
##      nodes: redis-service-redis-cluster.demo:6379
#      nodes: 10.250.1.162:30377
#    password: A1sHG18WUK
##    password: HNFjXZJN2p
#    lettuce:
#      pool:
#        max-active: 200 #连接池最大连接数（使用负值表示没有限制
#        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 20  # 连接池中的最大空闲连接
#        min-idle: 10 # 连接池中的最小空闲连接
#    timeout: 3000 # 读超时时间（毫秒）
#    connect-timeout: 2000 # 链接超时时间（毫秒）

server:
  port: 8080
